Add pretty timer
TouchInstinct/LeadKit pull request #281
Opened 2021-08-15 16:15 UTC by Loupehope

[TITimer](https://github.com/TouchInstinct/LeadKit/tree/feature/pretty_timer/TIFoundationUtils/Sources/TITimer)

2021-08-16 09:28 UTC, b0sya requested changes

2021-08-16 09:28 UTC, b0sya commented on TIFoundationUtils/Sources/TITimer/Sources/TITimer/Protocols/IInvalidatable.swift
> +public protocol IInvalidatable: AnyObject {
Не уверен что нужна приставка I в случае если название протокола оканчивается на able или -ible, потому что эти окончания и так указывают на то что это протокол

2021-08-16 09:28 UTC, b0sya commented on TIFoundationUtils/Sources/TITimer/Sources/TITimer/TITimer.swift
> +        NotificationCenter.default.removeObserver(self)
А зачем дважды отписываться?

2021-08-16 09:31 UTC, b0sya commented on Tests/TITimerTests/TITimerTests.swift
> +        // then
Пустую строку после then?

2021-08-16 10:02 UTC, Loupehope commented on Tests/TITimerTests/TITimerTests.swift
> +        // then
Привел к одному виду (без пустых строк)

2021-08-16 10:28 UTC, b0sya commented on TIFoundationUtils/Sources/TITimer/Sources/TITimer/Protocols/IInvalidatable.swift
> +public protocol IInvalidatable: AnyObject {
У них там немного бардак в этом плане, есть IUndoService, IAppBadgeResetter, LockLoaderDisplayable, StoryboardLoadable, но иногда проскакивают IAlertPresentable и подобные. Учитывая что последних вариантов сильно меньше, думаю это опечатки. А так, приставка I в любом названии интерфейса - это из стайлгайдов C#, но мы то на Swift пишем. В общем, предлагаю сделать такое правило: если к названию протокола не получается добавить able или ing, то добавляется приставка I. Данная приставка хорошо помогает когда необходимо написать протоколы к MVP

2021-08-16 10:51 UTC, Loupehope commented on TIFoundationUtils/Sources/TITimer/Sources/TITimer/Protocols/IInvalidatable.swift
> +public protocol IInvalidatable: AnyObject {
fxd

2021-08-16 10:54 UTC, b0sya approved these changes

2021-09-17 15:25 UTC, petropavel13 approved these changes

2021-09-17 16:06 UTC, merged