Feature/ti networking
TouchInstinct/LeadKit pull request #283
Opened 2021-09-14 14:18 UTC by petropavel13

Добавлен набор хелперов для построения сетевого слоя на основе swagger спецификации.

Предполагается интеграция с Moya, но это необязательно (в зависимостях только Alamofire)

2021-09-14 15:31 UTC, Loupehope commented on TINetworking/Sources/Mapping/BodyContent/ApplicationJsonBodyContent.swift
> +    private let encodingClosure: () throws -> Data
ThrowableResultClosure

2021-09-14 15:31 UTC, Loupehope commented on TINetworking/Sources/Mapping/BodyContent/ApplicationJsonBodyContent.swift
> +        self.encodingClosure = {
self не нужен

2021-09-14 15:31 UTC, Loupehope commented on TINetworking/Sources/Mapping/BodyContent/ApplicationJsonBodyContent.swift
> +open class ApplicationJsonBodyContent<Body>: BodyContent {
почему не наследуется от BaseContent? Кажется, никаких проблем не наблюдаю

2021-09-14 15:31 UTC, Loupehope commented on TINetworking/Sources/Mapping/OneOfMapping/AnyTypeMapping.swift
> +    private let mappingClosure: () -> Result<R, Error>
лучше располагать private выше

2021-09-14 15:31 UTC, Loupehope commented on TINetworking/Sources/Mapping/OneOfMapping/AnyTypeMapping.swift
> +    private let mappingClosure: () -> Result<R, Error>
ResultClosure

2021-09-14 15:31 UTC, Loupehope commented on TINetworking/Sources/Mapping/OneOfMapping/OneOfMappingError.swift
> +public struct OneOfMappingError: Error, CustomDebugStringConvertible {
OneOfMappingError -> MappingError так кажется более понятно, чем `одна из`

2021-09-14 15:31 UTC, Loupehope commented on TINetworking/Sources/Mapping/ResponseContent/ApplicationJsonResponseContent.swift
> +open class ApplicationJsonResponseContent<Model: Decodable>: ResponseContent {
BaseContent?

2021-09-14 15:31 UTC, Loupehope commented on TINetworking/Sources/Mapping/ResponseContent/MapResponseContent.swift
> +    private let decodeClosure: (Data) throws -> Model
ThrowableResultClosure

2021-09-14 15:31 UTC, Loupehope commented on TINetworking/Sources/Mapping/ResponseContent/MapResponseContent.swift
> +    func responseContent<T: Decodable, R>(_ tranfsorm: @escaping (T) -> R) -> MapResponseContent<R> {
Closure

2021-09-14 15:31 UTC, Loupehope commented on TINetworking/Sources/Mapping/ResponseContent/MapResponseContent.swift
> +    func decoding<T: Decodable, R>(to tranfsorm: @escaping (T) -> R) -> (Data) throws -> R {
Closure

2021-09-14 15:31 UTC, Loupehope commented on TINetworking/Sources/Mapping/ResponseContent/TextPlainResponseContent.swift
> +    public let mediaTypeName = CommonMediaTypes.textPlain.rawValue
свойства выше

2021-09-14 15:31 UTC, Loupehope commented on TINetworking/Sources/Parameters/Encoding/BaseUrlParameterEncoding.swift
> +        var filteredComponents: [(String, String)] = []
KeyValueTuple<String, String>

2021-09-14 15:31 UTC, Loupehope commented on TINetworking/Sources/Parameters/Encoding/BaseUrlParameterEncoding.swift
> +            let components: [KeyValueTuple<String, String>] = encoding.queryComponents(fromKey: key, value: parameter.value)
```swift
let components = encoding.queryComponents(fromKey: key, value: parameter.value)
                  .filter { !$0.value.isEmpty || $0.allowEmptyValue } 
```
кажется короче и понятнее

2021-09-14 15:31 UTC, Loupehope commented on TINetworking/Sources/Response/ResponseType+Decoding.swift
> +        where mappingStatusCode == statusCode && mappingMimeType == mimeType {
давай в одну строку с for, а то совсем не читается

2021-09-14 15:31 UTC, Loupehope commented on TINetworking/Sources/Parameters/Encoding/BaseUrlParameterEncoding.swift
> +    public init() {
public init() {}

2021-09-15 09:29 UTC, b0sya requested changes

2021-09-15 09:29 UTC, b0sya commented on TINetworking/Sources/Mapping/BodyContent/BodyContent.swift
> +public protocol BodyContent: Content {
Я бы переименовал, как как сейчас протокол называется как класс, можно например BodyContentStoring или BodyContentStorable

2021-09-15 09:29 UTC, b0sya commented on TINetworking/Sources/Mapping/BodyContent/ApplicationJsonBodyContent.swift
> +        self.encodingClosure = {
тоже self не нужен

2021-09-15 09:29 UTC, b0sya commented on TINetworking/Sources/Mapping/OneOfMapping/OneOfMappingError.swift
> +        var formattedString = "OneOf mapping failed for codingPath \(codingPath)\nwith following errors:\n"
А почему "OneOf" а не "One of"?

2021-09-15 09:29 UTC, b0sya commented on TINetworking/Sources/Mapping/ResponseContent/EmptyResponseContent.swift
> +    public func decodeResponse(data: Data) throws -> Void {
Может open? Бывают кейсы когда надо по особому декодировать ответ

2021-09-15 09:29 UTC, b0sya commented on TINetworking/Sources/Mapping/ResponseContent/ResponseContent.swift
> +public protocol ResponseContent: Content {
Тут тоже лучше либо добавить ing able либо I в начале, имхо

2021-09-15 09:29 UTC, b0sya commented on TINetworking/Sources/Parameters/Encoding/BaseUrlParameterEncoding.swift
> +        var filteredComponents: [(String, String)] = []
Имхо, но вот эти все обертки делают код менее понятным, особенно для новых разработчиков

2021-09-15 09:29 UTC, b0sya commented on TINetworking/Sources/Parameters/ParameterLocation.swift
> +public protocol ParameterLocation {}
Лучше использовать нейминг по гайдам свифта, например ParameterLocating

2021-09-15 09:29 UTC, b0sya commented on TINetworking/Sources/Request/Request.swift
> +    public var serverOverride: Server?
Увидев описанные выше параметры в первый раз, я понял их предназначение, а вот предназначение последних двух полей я не совсем понял, думаю лучше как нибудь по понятнее назвать, типа customServer и customServerVariables, если я правильно понял предназначение

2021-09-15 09:29 UTC, b0sya commented on TINetworking/Sources/Request/Request.swift
> +    public init(templatePath: String,
Мб можно в инит принимать какую нибудь структуру RequestConfiguration вместо кучи параметров

2021-09-15 09:29 UTC, b0sya commented on TINetworking/Sources/Response/ResponseType+Decoding.swift
> +        where mappingStatusCode == statusCode && mappingMimeType == mimeType {
Кажется что будет только хуже, 10 строчка сильно нагруженной получилась

2021-09-15 09:29 UTC, b0sya commented on TINetworking/Sources/Response/ResponseType.swift
> +public protocol ResponseType {
Может лучше что то типа Responsable

2021-09-15 09:29 UTC, b0sya commented on TINetworking/Sources/SessionFactory.swift
> +    public var serverTrustPolicies: [String: ServerTrustEvaluating]
По моему комментарий без смысловой нагрузки, поскольку повторяет название переменной

2021-09-16 09:28 UTC, squandev commented on TINetworking/Sources/Request/Request.swift
> +                headerParameters: HTTPHeaders? = nil,
возможно, здесь лучше присваивать HTTPHeaders(). когда делал эту часть, не учел это

2021-09-16 09:28 UTC, squandev commented on TINetworking/Sources/Response/StatusCodeMimeTypePairUnsupportedError.swift
> +    public override var debugDescription: String {
и здесь

2021-09-16 09:28 UTC, squandev commented on TINetworking/Sources/Server.swift
> +    private var defaultVariables: [KeyValueTuple<String, String>] {
и здесь

2021-09-16 09:28 UTC, squandev commented on TINetworking/Sources/Response/MimeTypeUnsupportedError.swift
> +    public var debugDescription: String {
по стайлгайдам, вроде var до init идет

2021-09-16 09:28 UTC, squandev commented on TINetworking/Sources/Mapping/BodyContent/ApplicationJsonBodyContent.swift
> +    private let encodingClosure: () throws -> Data
private до public по стайлгадам располагаем

2021-09-17 16:05 UTC, petropavel13 commented on TINetworking/Sources/Mapping/BodyContent/ApplicationJsonBodyContent.swift
> +    private let encodingClosure: () throws -> Data
не подключаю TISwiftUtils. посчитал, что тут оно того не стоит

2021-09-17 16:12 UTC, petropavel13 commented on TINetworking/Sources/Mapping/OneOfMapping/OneOfMappingError.swift
> +public struct OneOfMappingError: Error, CustomDebugStringConvertible {
задумка была другой https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/

Это ошибка при маппинге в один из возможных типов

2021-09-17 16:13 UTC, petropavel13 commented on TINetworking/Sources/Mapping/ResponseContent/MapResponseContent.swift
> +    func decoding<T: Decodable, R>(to tranfsorm: @escaping (T) -> R) -> (Data) throws -> R {
ну ладно, возможно стоит подключить SwiftUtils

2021-09-17 16:27 UTC, petropavel13 commented on TINetworking/Sources/Parameters/Encoding/BaseUrlParameterEncoding.swift
> +            let components: [KeyValueTuple<String, String>] = encoding.queryComponents(fromKey: key, value: parameter.value)
не сильно понятнее стало, я скажу

```swift
let components = encoding.queryComponents(fromKey: key, value: parameter.value)
                .filter { !$0.1.isEmpty || parameter.allowEmptyValue }
```

но я добавлю коммент

2021-09-17 16:28 UTC, petropavel13 commented on TINetworking/Sources/Response/ResponseType+Decoding.swift
> +        where mappingStatusCode == statusCode && mappingMimeType == mimeType {
чёт, я всё-таки за текущий вариант. в одну строчку линтер не пройдёт и в монитор не влезет на ревью

2021-09-17 16:28 UTC, petropavel13 commented on TINetworking/Sources/Mapping/ResponseContent/ApplicationJsonResponseContent.swift
> +open class ApplicationJsonResponseContent<Model: Decodable>: ResponseContent {
вроде обсудили, что так называть протоколы ок. если тут другая ситуация, отпишись

2021-09-17 16:30 UTC, petropavel13 commented on TINetworking/Sources/Mapping/ResponseContent/MapResponseContent.swift
> +    func responseContent<T: Decodable, R>(_ tranfsorm: @escaping (T) -> R) -> MapResponseContent<R> {
Я как бы ссылаюсь на первоисточник, но с грамматической точки зрения ты прав. https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/ оставлю как есть, только с маленькой буквы и в кавычках

2021-09-17 16:32 UTC, petropavel13 commented on TINetworking/Sources/Mapping/ResponseContent/MapResponseContent.swift
> +    func decoding<T: Decodable, R>(to tranfsorm: @escaping (T) -> R) -> (Data) throws -> R {
Как-то особенно декодировать ответ который ты игнорируешь? Это просто класс который ты используешь, когда тебе не нужно ничего делать с ответом, я лучше и сам класс сделаю public только

2021-09-17 16:37 UTC, petropavel13 commented on TINetworking/Sources/Request/Request.swift
> +    public init(templatePath: String,
которая будет соржать столько же параметров? :)
ну а если без шуток, то так и задумывается, что его использование предельно понятно, без лишних обёрток:

```swift
    static func apiV3MobileGeoCitySearchGeo(latitude: Double,
                                            longitude: Double,
                                            jsonEncoder: JSONEncoder = .init())
    -> TINetworking.Request<ApplicationJsonBodyContent<EmptyRequestBody>> {

        .init(templatePath: "/api/v3/mobile/geo/city/search/geo/",
              method: .get,
              requestBodyContent: ApplicationJsonBodyContent(body: EmptyRequestBody(), jsonEncoder: jsonEncoder),
              queryParameters: [
                "latitude": .init(value: latitude),
                "longitude": .init(value: longitude)
              ],
              acceptableStatusCodes: .successInternalErrorCodes)
    }
```

2021-09-17 16:40 UTC, petropavel13 commented on TINetworking/Sources/Request/Request.swift
> +                headerParameters: HTTPHeaders? = nil,
Moya работает с optional, предлагаю оставить как есть

```swift
// Moya.TargetType
public var headers: [String: String]?
```

2021-09-23 13:24 UTC, squandev commented on TINetworking/Sources/Request/Request.swift
> +                headerParameters: HTTPHeaders? = nil,
<img width="474" alt="Снимок экрана 2021-09-23 в 16 23 26" src="https://user-images.githubusercontent.com/40371778/134514827-81617c0c-f8c6-412b-be22-99e88510d555.png">

просто, мы бы смогли тогда здесь избегать дополнительной проверки, а от опционального значения вроде преимуществ нет

2021-09-27 12:56 UTC, Loupehope commented on TINetworking/TINetworking.podspec
> +  s.dependency 'Alamofire'
Возможно есть смысл указать конкретную версию?

2021-09-27 12:56 UTC, Loupehope approved these changes

2021-09-28 11:24 UTC, petropavel13 commented on TINetworking/TINetworking.podspec
> +  s.dependency 'Alamofire'
Хотел так оставить, чтобы либа не блокировала обновление Alamofire. можно заблокировать обновление мажорной версии, но давай подумаем об этом потом)

2021-09-28 11:44 UTC, svshkv commented on TINetworking/Sources/Mapping/OneOfMapping/AnyTypeMapping.swift
> +public struct AnyTypeMapping<R> {
может лучше назвать AnyTypeMapper?

2021-09-28 11:44 UTC, svshkv approved these changes

2021-09-30 07:20 UTC, petropavel13 commented on TINetworking/Sources/Request/Request.swift
> +                headerParameters: HTTPHeaders? = nil,
тут идея несколько иная. если у тебя словарь с параметрами == nil - значит можно с ним делать что угодно. если пустой, то так хотел разработчик который вызывает метод апи.

2021-09-30 07:33 UTC, b0sya approved these changes

2021-09-30 07:34 UTC, merged