Easy alerts presentation
TouchInstinct/LeadKit pull request #315
Opened 2022-07-25 14:12 UTC by castlele

## Вью на которой будет показываться алерт, должна конформить протокол PresentationContext
Для облегчения работы существуют `UIKitContext` и `SwiftUIContext`. *UIViewController* и *SwiftUI.View* могут без дополнительных изменений соответствовать данным протоколам:
```swift
class ViewController: UIViewController, UIKitContext {
    // view controller implementation
}

struct ContentView: View, SwiftUIContext {
    var body: some View {
        // body of the view
    }
}
```

## Если нужно показывать кастомные алерты (например, из других библиотек), необходимо, чтобы этот алерт конформил AlertPresentable
Стандартный `UIAlertController` уже соответствует данному протоколу

## Пример использования алертов в UIKit
```swift
class ViewController: UIViewController, UIKitContext {

    let factory = AlertFactory()

    @IBAction private func showAlert(sender: UIButton?) {
        factory
            .alert(title: "title",
                   message: "message",
                   tint: .systemBlue,
                   actions: [
                        AlertAction(title: "Ok", style: .default, action: nil),
                        AlertAction(title: "Cancel", style: .cancel, action: nil)
                   ])
            .present(on: self)
    }
}
```

## Пример использования алертов в SwiftUI
```swift
import PopupDialog

struct ContentView: View {

    private let factory = AlertFactory()

    @State private var isPresentedAlert = false
    @State private var isPresentedCustomAlert = false
    @State private var alertDescription: AlertDescriptor = .init()

    var body: some View {
        VStack(spacing: 20) {
            Button("Show dialogue from sui") {
                factory.dialogueAlert(title: "HELLO").present(on: self)
            }

            Button("Show dialogue with binding property from sui") {
                alertDescription = factory.dialogueAlert(title: "HELLO")
                isPresentedAlert = true
            }

            Button("Show alert from sui") {
                factory.okAlert(title: "title", message: "message").present(on: self)
            }

            Button("Show alert with binding property") {
                alertDescription = factory.okAlert(title: "title", message: "message")
                isPresentedAlert = true
            }

            Button("Show custom alert with binding property") {
                alertDescription = factory.okAlert(title: "title", message: "message")
                isPresentedCustomAlert = true
            }
        }
        .alert(isPresented: $isPresentedAlert, on: self, alert: alertDescription)
        .alert(isPresented: $isPresentedCustomAlert, on: self, alertDescriptor: alertDescription) {
            PopupDialog(title: $0.title, message: $0.message)
                .configured(with: $0)
        }
    }
}
```

## Пример использования кастомных алертов из библиотеки PopupDialog
```swift
import PopupDialog

extension PopupDialog: AlertPresentable {
    @discardableResult
    public func configured(with configuration: AlertDescriptor) -> Self {
        title = configuration.title

        for action in configuration.actions {
            addButton(DefaultButton(title: action.title, action: action.action))
        }

        return self
    }

    public func present(on context: PresentationContext, completion: VoidClosure?) {
        context.present(self, animated: true, completion: completion)
    }
}

class ViewController: UIViewController, UIKitContext {

    let factory = AlertFactory()
    
    @IBAction private func customAlertDidPress(sender: UIButton?) {
        factory
            .retryAlert(title: "Retry", message: "LeadKit") { [weak self] in
                self?.okAlertDidPress(sender: sender)
            }
            .present(on: self) {
                PopupDialog(title: $0.title, message: $0.message)
                    .configured(with: $0)
            }
    }
}
```

 ## Примеры использования стандартных алертов
 ```swift
 // Ok alert
 func presentOkAlert() {
     factory
         .okAlert(title: "Title", message: "Message")
         .present(on: self)
 }

 // Retry alert
 func presentRetryAlert() {
     factory
         .retryAlert(title: "Title", message: "Message") { [weak self] in
             self?.presentOkAlert()
         }
         .present(on: self)
 }

 // Dialogue alert
 func presentDialogueAlert() {
     factory
         .dialogueAlert(title: "Title", message: "Message")
         .present(on: self)
 }
 ```

## Примеры алертов
<img width="292" src="https://user-images.githubusercontent.com/69932531/180796804-f3080874-25a4-46d6-aa8c-3204fd5764fc.png" align="left"></img>

<img width="292" src="https://user-images.githubusercontent.com/69932531/180796973-d9ebf7b8-0500-4bd8-a525-52885cd3a241.png" align="right"></img>

<img width="292" src="https://user-images.githubusercontent.com/69932531/180797038-07e2433d-5ad9-43a4-b8ba-7364ed2a228d.png" align="center"></img>

2022-07-25 14:41 UTC, petropavel13 requested changes

2022-07-25 14:41 UTC, petropavel13 commented on TIUIElements/Sources/Alerts/Factories/AlertFactory.swift
> +
новая строка кажется лишней

2022-07-25 14:41 UTC, petropavel13 commented on TIUIElements/Sources/Alerts/Helpers/AlertDescriptor+Helpers.swift
> +    public func present(on context: PresentationContext, completion: VoidClosure? = nil) {
prefer public extension over public methods in extension

2022-07-25 14:41 UTC, petropavel13 commented on TIUIElements/Sources/Alerts/Helpers/UIAlertController+AlertPresentable.swift
> +    public func configured(with configuration: AlertDescriptor) -> Self {
аналогично

2022-07-25 14:41 UTC, petropavel13 commented on TIUIElements/Sources/Alerts/Helpers/UIAlertController+AlertPresentable.swift
> +import TISwiftUtils
вроде лишний импорт

2022-07-25 14:41 UTC, petropavel13 commented on TIUIElements/Sources/Alerts/Models/DefaultAlertLocalizationProvider.swift
> +    public private(set) var bundle: Bundle
зачем нам private(set) var?)
я последнее время в либах оставляю возможность менять изначальные настройки (property)

2022-07-25 14:41 UTC, petropavel13 commented on TIUIElements/Sources/Alerts/Protocols/PresentationContext.swift
> +public protocol PresentationContext {
предлагаю AlertPresentationContext, чтобы не путать с UIViewController presentation context, типа https://developer.apple.com/documentation/uikit/uiviewcontroller/1621456-definespresentationcontext

2022-07-25 14:41 UTC, petropavel13 commented on TIUIElements/Sources/Alerts/Protocols/SwiftUIContext.swift
> +public protocol SwiftUIContext: PresentationContext {
SwiftUIAlertContext

2022-07-25 14:41 UTC, petropavel13 commented on TIUIElements/Sources/Alerts/Protocols/SwiftUIContext.swift
> +}
если мы презентуем на UIViewController, то надо передать в параметре на каком.
и .windows.first вроде уже не работает в каких-то случаях типа SceneDelegate (не точно, но в любом случае грязновато)

2022-07-25 14:41 UTC, petropavel13 commented on TIUIElements/Sources/Alerts/Protocols/UIKitContext.swift
> +public protocol UIKitContext: PresentationContext { }
UIKitAlertContext

2022-07-25 14:53 UTC, castlele commented on TIUIElements/Sources/Alerts/Helpers/UIAlertController+AlertPresentable.swift
> +import TISwiftUtils
Для использования `VoidClosure` импорт нужен (43 строчка)
```swift
extension UIAlertController: AlertPresentable {
    public func present(on context: PresentationContext, completion: VoidClosure?) {
        context.present(self, animated: true, completion: completion)
    }
}
```

2022-07-26 08:42 UTC, petropavel13 commented on TIUIElements/Sources/Alerts/Helpers/UIAlertController+AlertPresentable.swift
> +import typealias TISwiftUtils.VoidClosure
слишком хардкорно)
если нужен импорт - пусть будет, усложнять не надо

2022-07-26 08:42 UTC, petropavel13 commented on TIUIElements/Sources/Alerts/Protocols/AlertPresentable.swift
> +import Foundation
Foundation лишний (не критично)

2022-07-26 08:42 UTC, petropavel13 commented on TIUIElements/Sources/Alerts/Protocols/SwiftUIAlertContext.swift
> +@available(iOS 13, *)
вроде как available уже и не нужен 🤷

2022-07-26 08:42 UTC, petropavel13 commented on TIUIElements/Sources/Alerts/Protocols/SwiftUIAlertContext.swift
> +import SwiftUI
и импорт

2022-07-26 08:42 UTC, petropavel13 commented on TIUIElements/Sources/Alerts/Helpers/View+Helpers.swift
> +import SwiftUI
вроде как это не соберётся с deployment target ниже требуемой
через canImport тоже не получится в либе сделать из-за каких-то особенностей cocoapods, поэтому предлагаю вынести в TISwiftUIElements

2022-07-26 08:42 UTC, petropavel13 commented on TIUIElements/Sources/Alerts/Protocols/SwiftUIAlertContext.swift
> +@available(iOS 13, *)
и сразу в TISwiftUIElements

2022-07-26 12:16 UTC, petropavel13 commented on TISwiftUICore/Sources/Alerts/Modifiers/View+Alerts.swift
> +import TIUIElements
вроде этого импорта тут быть не должно

2022-07-26 12:16 UTC, petropavel13 commented on TISwiftUICore/TISwiftUICore.podspec
> +  s.dependency 'TIUIElements', s.version.to_s
и этой зависимости

2022-07-26 12:24 UTC, petropavel13 reviewed
Package.swift не поправил

2022-07-26 12:24 UTC, petropavel13 commented on TIUIKitCore/Sources/Extensions/Alerts/AlertDescriptor+Helpers.swift
> +                        completion: VoidClosure? = nil) {
выравнивание

2022-07-27 08:25 UTC, petropavel13 approved these changes

2022-07-27 08:52 UTC, matteocarrera commented on TISwiftUICore/README.md
> +> SwiftUI views should conform to protocol `SwiftUIAlertContext` to present alert
`... to present an alert` в случае единственного числа или `... to present alerts` в случае множественного

2022-07-27 08:56 UTC, matteocarrera commented on TIUIKitCore/README.md
> +There are `UIKitAlertContext` protocol that are designed to make it easier to work with `AlertPresentationContext` protocol. By default, no changes need to be made for UIKit view controllers to make
There is a `UIKitAlertContext` protocol designed to make it easier to work with `AlertPresentationContext` protocol.

2022-07-27 08:57 UTC, matteocarrera commented on TIUIKitCore/Sources/Alerts/Factories/AlertFactory.swift
> +    public var localizationProvider: AlertLocalizationProvider
1. Почему не `private`?
2. Почему не `let`? У нас есть возможность изменять `provider`?

2022-07-27 08:58 UTC, matteocarrera commented on TIUIKitCore/Sources/Alerts/Factories/AlertFactory.swift
> +    /// - Returns: Alert descriptor, which can be used to present alert view.
перед `which` можно убрать запятую

2022-07-27 08:58 UTC, matteocarrera commented on TIUIKitCore/Sources/Alerts/Factories/AlertFactory.swift
> +    /// - Returns: Alert descriptor, which can be used to present alert view.
`an alert view`

2022-07-27 08:59 UTC, matteocarrera commented on TIUIKitCore/Sources/Alerts/Factories/AlertFactory.swift
> +    static func simpleAction(_ title: String,
А что за `simpleAction`? Это что-то вроде заглушки, на которую мы ничего не можем повесить?

2022-07-27 09:00 UTC, matteocarrera commented on TIUIKitCore/Sources/Alerts/Models/AlertAction.swift
> +// struct describe alert button information
`A struct describes an alert button information`

2022-07-27 09:01 UTC, matteocarrera commented on TIUIKitCore/Sources/Alerts/Models/AlertDescriptor.swift
> +/// Struct describes alert data
`A struct describes an alert data`

2022-07-27 09:01 UTC, ElysiumWhale commented on TISwiftUICore/Sources/Alerts/Protocols/SwiftUIAlertContext.swift
> +public extension SwiftUIAlertContext {
А где находится соответствие View данному протоколу? Пока что не понимаю, как это будет работать в SwiftUI, если в качестве контекста презентации в примере указан self

2022-07-27 09:02 UTC, matteocarrera commented on TIUIKitCore/Sources/Alerts/Protocols/AlertPresentable.swift
> +public protocol AlertPresentable {
Было бы круто получить краткое описание протокола, чтобы понимать, для чего он может быть использован

2022-07-27 09:02 UTC, matteocarrera commented on TIUIKitCore/Sources/Alerts/Protocols/AlertPresentationContext.swift
> +public protocol AlertPresentationContext {
Было бы круто получить краткое описание протокола, чтобы понимать, для чего он может быть использован

2022-07-27 09:02 UTC, matteocarrera commented on TIUIKitCore/Sources/Alerts/Protocols/UIKitAlertContext.swift
> +public protocol UIKitAlertContext: AlertPresentationContext { }
Было бы круто получить краткое описание протокола, чтобы понимать, для чего он может быть использован

2022-07-27 09:03 UTC, matteocarrera commented on TIUIKitCore/Sources/Localization/AlertsLocalization/AlertLocalizationProvider.swift
> +public protocol AlertLocalizationProvider {
Было бы круто получить краткое описание протокола, чтобы понимать, для чего он может быть использован

2022-07-27 09:03 UTC, matteocarrera commented on TIUIKitCore/Sources/Localization/AlertsLocalization/DefaultAlertLocalizationProvider.swift
> +/// Provide default localization for alerts' buttons
`Provides a default localization....`

2022-07-27 09:04 UTC, matteocarrera commented on TIUIKitCore/Sources/Localization/AlertsLocalization/DefaultAlertLocalizationProvider.swift
> +    public var bundle: Bundle
Почему не `let`? Можем изменять?

2022-07-27 09:10 UTC, petropavel13 commented on TIUIKitCore/Sources/Localization/AlertsLocalization/AlertLocalizationProvider.swift
> +public protocol AlertLocalizationProvider {
вроде из названия понятно) провайдер локализации для алерта

2022-07-27 09:10 UTC, petropavel13 commented on TIUIKitCore/Sources/Alerts/Protocols/AlertPresentationContext.swift
> +public protocol AlertPresentationContext {
тут плюсану

2022-07-27 09:10 UTC, petropavel13 commented on TIUIKitCore/Sources/Alerts/Protocols/UIKitAlertContext.swift
> +public protocol UIKitAlertContext: AlertPresentationContext { }
а тут нет)

2022-07-27 09:12 UTC, petropavel13 commented on TIUIKitCore/Sources/Alerts/Factories/AlertFactory.swift
> +    public var localizationProvider: AlertLocalizationProvider
я предлагаю в бейзлибах делать более гибкую настройку. хочешь в конструкторе задал и забыл, хочешь поменял потом через свойство и т.п.

2022-07-27 09:13 UTC, petropavel13 commented on TIUIKitCore/Sources/Localization/AlertsLocalization/DefaultAlertLocalizationProvider.swift
> +    public var bundle: Bundle
да, комментом выше описал мотивацию такого решения

2022-07-27 09:13 UTC, castlele commented on TISwiftUICore/Sources/Alerts/Protocols/SwiftUIAlertContext.swift
> +public extension SwiftUIAlertContext {
Нет дефолтного соответствия. Исходя из расчета Вани (https://docs.google.com/spreadsheets/d/13p4rz1wueQEa3nqi55XhXWP7rRs_2obVNNc8ZheUsZo/edit#gid=0) касательно навигации в sui, вьюшки будут находится во ViewController'е. Так при соответствии данному протоколу необходимо будет передать этот конроллер

Фиксанул описание PR

2022-07-27 09:37 UTC, castlele commented on TIUIKitCore/Sources/Alerts/Factories/AlertFactory.swift
> +    public var localizationProvider: AlertLocalizationProvider
Ваня говорит, что в последнее время оставляет возможность менять переменные
https://github.com/TouchInstinct/LeadKit/pull/315#discussion_r928958290

2022-07-27 09:40 UTC, castlele commented on TIUIKitCore/Sources/Alerts/Factories/AlertFactory.swift
> +    static func simpleAction(_ title: String,
Вспомогательный метод, чтобы можно было сделать `AlertAction` без action

2022-07-27 09:43 UTC, castlele commented on TIUIKitCore/Sources/Localization/AlertsLocalization/DefaultAlertLocalizationProvider.swift
> +    public var bundle: Bundle
Ваня говорит, что в последнее время оставляет возможность менять переменные
https://github.com/TouchInstinct/LeadKit/pull/315#discussion_r928958290

2022-07-27 10:14 UTC, castlele commented on TIUIKitCore/Sources/Alerts/Protocols/AlertPresentable.swift
> +public protocol AlertPresentable {
Имллементация данного протокола говорит о том, что алерт может быть показан из контекста. По дефолту стандартный UIAlertController соответствует протоколу. Соответственно, при использовании кастомного алерта, он также должен соответствовать протоколу:

```swift
import PopupDialog

extension PopupDialog: AlertPresentable {
    @discardableResult
    public func configured(with configuration: AlertDescriptor) -> Self {
        title = configuration.title

        for action in configuration.actions {
            addButton(DefaultButton(title: action.title, action: action.action))
        }

        return self
    }

    public func present(on context: AlertPresentationContext, completion: VoidClosure?) {
        context.present(self, animated: true, completion: completion)
    }
}
```

Также добавил в описание PR

2022-07-27 10:14 UTC, castlele commented on TIUIKitCore/Sources/Alerts/Protocols/AlertPresentationContext.swift
> +public protocol AlertPresentationContext {
Имллементация данного протокола говорит о том, что с данного объекта (контекста) может быть показан алерт

Добавил описание в PR

2022-07-27 11:57 UTC, matteocarrera commented on TIUIKitCore/Sources/Alerts/Protocols/AlertPresentable.swift
> +public protocol AlertPresentable {
Так добавь это прямо как документация к протоколу внутри файла

2022-07-27 11:58 UTC, matteocarrera commented on TIUIKitCore/Sources/Alerts/Protocols/UIKitAlertContext.swift
> +public protocol UIKitAlertContext: AlertPresentationContext { }
Как-то странно тогда половину документировать, а половину нет. Лучше уж какое-то минимальное описание добавить ко всему, чтобы придерживаться единого стиля

2022-07-27 13:12 UTC, matteocarrera commented on TISwiftUICore/Sources/Alerts/Protocols/SwiftUIAlertContext.swift
> +/// ```
Да я думаю, что прям пример можно и не добавлять, его можно выделить в Samples какие-нибудь, здесь будет достаточно просто первой строки

2022-07-27 13:13 UTC, matteocarrera commented on TIUIKitCore/Sources/Alerts/Protocols/AlertPresentable.swift
> +///
И здесь аналогично, можно просто оставить текст общий, пример либо удалить, либо вынести в Samples

2022-07-27 13:13 UTC, matteocarrera commented on TIUIKitCore/Sources/Alerts/Protocols/UIKitAlertContext.swift
> +/// ```
И тут аналогично

2022-07-28 08:55 UTC, merged