Feature/ecommerce
TouchInstinct/LeadKit pull request #319
Opened 2022-08-01 08:18 UTC by boykogri

2022-08-01 13:04 UTC, petropavel13 requested changes

2022-08-01 13:04 UTC, petropavel13 commented on TIEcommerce/Sources/Cart protocols/Receipt.swift
> +import Foundation
не вижу никакого смысла в этих протоколах

2022-08-01 13:04 UTC, petropavel13 commented on TIEcommerce/Sources/Cart protocols/CartUpdatable.swift
> +}
это должно быть в CartService

2022-08-01 13:04 UTC, petropavel13 commented on TIEcommerce/Sources/Cart protocols/CartEditable.swift
> +import Foundation
и эти протоколы не нужны

2022-08-01 13:27 UTC, boykogri commented on TIEcommerce/Sources/Models/CartProduct.swift
> +    var variants: [CartProduct?] { get }
Просто в примере ответа был null
<img width="317" alt="image" src="https://user-images.githubusercontent.com/47790828/182158414-4269a301-e610-43de-ae1c-6c1ea18db426.png">

2022-08-01 13:32 UTC, boykogri commented on TIEcommerce/Sources/Cart protocols/CartUpdatable.swift
> +}
есть ли смысл в from localCart: Cart, если он и так хранится в CartService?

2022-08-01 14:45 UTC, petropavel13 requested changes
Changelog нужно обновить

2022-08-01 14:45 UTC, petropavel13 commented on TIEcommerce/Sources/Classes/CartRequestExecutor.swift
> +        _ = executionClosure { [weak self] in
должно присваиваться в executingRequest

2022-08-01 14:45 UTC, petropavel13 commented on TIEcommerce/Sources/Classes/CartRequestExecutor.swift
> +        if shouldRetry(failure: failure) && 0 < 3 {
серьезно? ты смотрел на код, который скопировал?

2022-08-01 14:45 UTC, petropavel13 commented on TIEcommerce/Sources/Classes/CartRequestExecutor.swift
> +import TIFoundationUtils
заголовка файла не хватает

2022-08-01 14:45 UTC, petropavel13 commented on TIEcommerce/Sources/Models/BaseErrorResponseBody.swift
> +protocol BaseErrorResponseBody: Decodable, Hashable {
public

2022-08-01 14:45 UTC, petropavel13 commented on TIEcommerce/Sources/Models/Cart.swift
> +protocol Cart {
public

2022-08-01 14:45 UTC, petropavel13 commented on TIEcommerce/Sources/Models/CartProduct.swift
> +protocol CartProduct {
public

2022-08-01 14:45 UTC, petropavel13 commented on TIEcommerce/Sources/Models/CartService.swift
> +protocol CartPublisher {
public

2022-08-01 14:45 UTC, petropavel13 commented on TIEcommerce/Sources/Models/CartService.swift
> +    associatedtype Cart
associatedtype CartType: Cart
associatedtype CartProductType: CartProduct

2022-08-01 14:45 UTC, petropavel13 commented on TIEcommerce/Sources/Models/CartService.swift
> +    var localCart: Cart? { get }
аналогично, с associatedtype

2022-08-01 14:45 UTC, petropavel13 commented on TIEcommerce/Sources/Models/Price.swift
> +protocol Price {
public

2022-08-01 14:45 UTC, petropavel13 commented on TIEcommerce/Sources/Models/Promocode.swift
> +protocol Promocode {
public

2022-08-01 14:45 UTC, petropavel13 commented on TIEcommerce/Sources/Models/CartService.swift
> +    func subscribeOnProductChanging(productId: Int, completion:  ParameterClosure<CartProduct>) -> Cancellable
лучше сразу перенести в CartService

2022-08-01 14:45 UTC, petropavel13 commented on TIEcommerce/TIEcommerce.podspec
> +  s.version          = '1.25.0'
там уже 1.26, должна быть. и у остальных тоже надо поднять скриптом https://github.com/TouchInstinct/LeadKit/blob/master/project-scripts/bump_version.sh

2022-08-01 14:46 UTC, petropavel13 commented on TIEcommerce/Sources/Cart protocols/CartUpdatable.swift
> +}
нет

2022-08-01 14:47 UTC, petropavel13 commented on TIEcommerce/Sources/Models/CartProduct.swift
> +    var variants: [CartProduct?] { get }
это дока так отрендерила ссылку модели на саму себя

2022-08-01 14:49 UTC, petropavel13 commented on TIEcommerce/Sources/Models/CartProduct.swift
> +    var variants: [CartProduct?] { get }
но вообще там variants должны быть другой моделью, я поправлю

2022-08-02 01:55 UTC, boykogri commented on TIEcommerce/Sources/Classes/CartRequestExecutor.swift
> +        if shouldRetry(failure: failure) && 0 < 3 {
ой, исправил😁

2022-08-02 02:23 UTC, boykogri commented on TIEcommerce/TIEcommerce.podspec
> +  s.version          = '1.25.0'
А как скрипт запустить?
<img width="573" alt="image" src="https://user-images.githubusercontent.com/47790828/182277994-07ccaf30-fd3e-4f58-8ab1-8f24bf4e01e1.png">

2022-08-02 08:02 UTC, petropavel13 commented on TIEcommerce/Sources/Models/BaseErrorResponseBody.swift
> +public protocol BaseErrorResponseBody: Decodable, Hashable {
скорей всего Hashable мешает использовать модель в методах, но Hashable ни Decodable не нужен тут

2022-08-02 08:14 UTC, boykogri commented on TIEcommerce/Sources/Models/CartService.swift
> +    var localCart: CartType? { get }
Ориентировался по петшопу, можно легко почистить корзину cart = nil

2022-08-02 12:02 UTC, petropavel13 reviewed
записи в changelog не вижу

2022-08-02 12:02 UTC, petropavel13 commented on TIEcommerce/TIEcommerce.podspec
> +  s.dependency 'TIFoundationUtils', s.version.to_s
TINetworking забыл

2022-08-02 12:02 UTC, petropavel13 commented on TIEcommerce/TIEcommerce.podspec
> +  s.ios.deployment_target = '10.0'
и когда подключишь TINetworking проверь, какая там deployment target

2022-08-02 14:40 UTC, boykogri commented on TIEcommerce/TIEcommerce.podspec
> +  s.ios.deployment_target = '10.0'
там же тоже 10
<img width="681" alt="image" src="https://user-images.githubusercontent.com/47790828/182401974-aa1147e9-fe67-49d8-b7a6-c5a6127a559c.png">

2022-08-03 08:05 UTC, EastHell commented on TIEcommerce/Sources/Classes/CartRequestExecutor.swift
> +
Предлагаю удалить пустую строчку между тайпалиасами. В ней вроде бы нет смысла.

2022-08-03 08:07 UTC, EastHell commented on TIEcommerce/Sources/Classes/CartRequestExecutor.swift
> +    private var attemptsLeft: Int
Согласано [стайлгайдам](https://github.com/TouchInstinct/Styleguide/blob/master/IOS/Guides/FileDesignRecommendations/File_Design_Recommendations_Guide.md#%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%B7%D0%B8%D1%86%D0%B8%D1%8F-%D1%84%D0%B0%D0%B9%D0%BB%D0%B0) сначала стоит указывать приватные константы, потом приватные переменные, потом публичные константы, потом публичные переменные.

2022-08-03 08:13 UTC, EastHell commented on TIEcommerce/Sources/Classes/CartRequestExecutor.swift
> +        executingRequest?.cancel()
Возможно стоит заменить на просто `cancel()`

2022-08-03 08:30 UTC, EastHell commented on TIEcommerce/Sources/Classes/CartRequestExecutor.swift
> +open class CartRequestExecutor<S: Decodable, AE: Decodable, NE>: Cancellable {
Название `CartRequestExecutor` не очень подходит для данного класса. Поскольку кроме дефолтного значения числа попыток - тут в общем то ничего конкретного с корзиной не происходит. Больше похоже на просто `RequestExecutor` какой-нибудь.

2022-08-03 08:32 UTC, EastHell commented on TIEcommerce/Sources/Models/CartProduct.swift
> +    ///Сколько единиц есть доступно
```suggestion
    ///Количество доступных единиц
```

2022-08-03 09:36 UTC, EastHell approved these changes

2022-08-03 11:30 UTC, petropavel13 approved these changes

2022-08-03 15:15 UTC, merged